language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
script:
  - npm ci
  - npm test -- -u --ci
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - npm ci
        - npm install -g expo-cli
        - npx expo login --non-interactive -u cyhamumich
        - npx expo publish --non-interactive
branches:
  except:
  - develop
  - eject
