export const colors =
{
  appBackground: '#fff',
  text: '#000',
  inputPlaceholder: '#0005',
  spinner: '#00A89D',
  accentBackground: '#00A89D',
  button: '#00A89D',
  selectedButton: '#00655e',
  selectedButtonText: '#fff',
  uncheckedColor: 'lightgray',
  duration: '#d3d3d3cc',
  difficultyTag: '#89cff0',
  topicTag: '#d7efc0',
  modalButtons: '#d3d3d3',
  modalBackground: '#fff',
  modalBorder: '#000',
  transparentButton: 'rgba(52, 52, 52, 0)',
  minimumSliderColor: '#967eda',
  maximumSliderColor: '#000',
  journalTextBackground: '#F3F3F3',
};